name: Build Flutter APK

on:
  push:
    branches:
      - main  # Build when pushing to the main branch
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # Java setup
          java-version: '17'

      # Check Java version
      - name: Check Java version
        run: java -version

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.2'
          channel: stable  # Stable channel for Flutter

      - name: Flutter version check
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      # Build APKs split by ABI
      - name: Build APK (split by ABI)
        run: flutter build apk --release --split-per-abi

      # Build App Bundle
      - name: Build App Bundle
        run: flutter build appbundle --release

      # Upload APKs for different architectures
      - name: Upload APK (arm64-v8a)
        uses: actions/upload-artifact@v4
        with:
          name: release-apk-arm64-v8a
          path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk

      - name: Upload APK (armeabi-v7a)
        uses: actions/upload-artifact@v4
        with:
          name: release-apk-armeabi-v7a
          path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk

      - name: Upload APK (x86_64)
        uses: actions/upload-artifact@v4
        with:
          name: release-apk-x86_64
          path: build/app/outputs/flutter-apk/app-x86_64-release.apk

      # Upload the app bundle
      - name: Upload App Bundle
        uses: actions/upload-artifact@v4
        with:
          name: release-appbundle
          path: build/app/outputs/bundle/release/app.aab